[profile.default]
src = "src"
out = "artifacts"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200
auto_detect_solc = true

remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  "permit2/=lib/permit2/",
  "solmate/=lib/permit2/lib/solmate/"
]

[rpc_endpoints]
mainnet = "https://forno.celo.org/"
celo_sepolia = "https://forno.celo-sepolia.celo-testnet.org/"
